#!/usr/bin/env bash

source_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
cd $source_dir

COLOUR_GREEN='\033[0;32m'
COLOUR_YELLOW='\033[1;33m'
COLOUR_PURPLE='\033[0;35m'
COLOUR_RED='\033[0;31m'
COLOUR_OFF='\033[0;00m'
CLEAR_LINE='\033[2K'

_ERROR_="${COLOUR_RED}[ERROR]${COLOUR_OFF}"
_INFO_="${COLOUR_PURPLE}[INFO]${COLOUR_OFF}"
_DEBUG_="${COLOUR_YELLOW}[DEBUG]${COLOUR_OFF}"

opt_verbose=false

printf_v() {
	if $opt_verbose;
	then
		printf $1;
	fi
}
printf_nv() {
	if ! $opt_verbose;
	then
		printf $1;
	fi
}

## Read Flags
OPTIND=1
while getopts ":v" opt; do
  case "$opt" in
    v) # Debug
      opt_verbose=true
      ;;
    ?) # Illegal Option
      echo -e "$_ERROR_ Illegal option '$OPTARG'"
      exit 3
      ;;
  esac
done
for i in `seq 2 $OPTIND`; do shift; done

# Use libdeflate if available for small compression gain
# 'sudo apt install libdeflate-tools'
# It would be great to use brotli, however firefox does not support brotli over HTTP as it can break MITM proxies.
COMPRESS_BIN="libdeflate-gzip -12 -k"
if ! command -v libdeflate-gzip &> /dev/null
then

    if ! command -v gzip &> /dev/null
	then
	    echo "Error: At least one of 'gzip' or 'libdeflate-gzip' needs to be installed.";
	    exit 1;
	fi
    COMPRESS_BIN="gzip -9k"
fi



printf "$_INFO_ Packing web files.. ";
printf_v "\n"

printf_v "Clearing htdist/..\n"
mkdir -p src/htdist/
rm -f src/htdist/*.gz

printf_v "Compressing files..\n"
for file in $(find src/htsrc/ -type f)
do
	$COMPRESS_BIN $file
done

mv src/htsrc/*.gz src/htdist/

# Touch source file to update compile
touch src/main.rs;

printf "${COLOUR_GREEN}OK${COLOUR_OFF}\n";