#!/usr/bin/env bash

source_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
cd $source_dir

./build_htdocs;
#cargo +nightly flash --connect-under-reset --chip STM32F767ZITx --release;
cargo +nightly flash --connect-under-reset --chip STM32H753ZITx --release;
